source "http://rubygems.org"

gem "nanoc"
gem "rake"
gem "adsf"
gem "kramdown"
gem "haml"
gem "sass"
gem "less"
gem "therubyracer", "0.12.0", platforms: :ruby
gem "coffee-script"
gem "uglifier"
gem "w3c_validators"
gem "systemu"
gem "sprockets"
gem "sprockets-helpers"
gem "sprockets-sass"
gem "sprockets-less"
gem "nanoc-sprockets-filter"
gem "nanoc-gzip-filter"
